import type { PricingTier } from '@/types'

export const AGENCY_PLANS: readonly PricingTier[] = [
  {
    id: 'launch',
    name: 'Launch',
    tagline: 'Get found online',
    price: 499,
    currency: 'USD',
    period: 'month',
    ctaLabel: 'Get Started',
    features: [
      { label: '3 target keywords tracked',    included: true  },
      { label: 'Google My Business setup',      included: true  },
      { label: 'Basic on-page SEO',             included: true  },
      { label: '8 social posts / month',        included: true  },
      { label: 'Monthly analytics report',      included: true  },
      { label: 'Paid ads management',           included: false },
      { label: 'Competitor analysis',           included: false },
    ],
  },
  {
    id: 'grow',
    name: 'Grow',
    tagline: 'Scale your reach every month',
    price: 999,
    currency: 'USD',
    period: 'month',
    ctaLabel: 'Get Started',
    isRecommended: true,
    badge: 'Popular',
    features: [
      { label: '10 target keywords tracked',    included: true },
      { label: 'Full on-page + off-page SEO',   included: true },
      { label: '20 social posts / month',       included: true },
      { label: 'Google + Meta Ads management',  included: true },
      { label: 'Weekly analytics report',       included: true },
      { label: 'Competitor analysis',           included: true },
      { label: 'Blog content (4/month)',         included: true },
    ],
    extraFeatures: [
      { label: 'Landing page CRO audit',        included: true },
      { label: 'Priority Whatsapp support',     included: true },
    ],
  },
  {
    id: 'scale',
    name: 'Scale',
    tagline: 'Dominate your niche',
    price: 'custom',
    currency: 'USD',
    period: 'month',
    ctaLabel: 'Book a Call',
    features: [
      { label: 'Unlimited keywords tracked',    included: true },
      { label: 'Full SEO + PR strategy',        included: true },
      { label: 'Daily social posts',            included: true },
      { label: 'Multi-channel ad campaigns',    included: true },
      { label: 'Dedicated account manager',     included: true },
      { label: 'Custom content strategy',       included: true },
      { label: 'Influencer outreach',           included: true },
    ],
  },
]

export const WEBSITE_PLANS: readonly PricingTier[] = [
  {
    id: 'basic',
    name: 'Basic',
    tagline: 'Your first proper website',
    price: 299,
    currency: 'USD',
    period: 'one-time',
    delivers: '7–10 days',
    ctaLabel: 'Get Started',
    features: [
      { label: 'Up to 5 pages',             included: true  },
      { label: 'Fully responsive design',    included: true  },
      { label: 'Basic on-page SEO',          included: true  },
      { label: 'Contact form',               included: true  },
      { label: '1 revision round',           included: true  },
      { label: 'Framer / Webflow build',     included: true  },
      { label: 'CMS / blog',                 included: false },
    ],
  },
  {
    id: 'growth-site',
    name: 'Growth Site',
    tagline: 'Built to convert visitors',
    price: 599,
    currency: 'USD',
    period: 'one-time',
    delivers: '14 days',
    ctaLabel: 'Get Started',
    isRecommended: true,
    badge: 'Popular',
    features: [
      { label: 'Up to 10 pages',             included: true },
      { label: 'Fully responsive design',    included: true },
      { label: 'Advanced on-page SEO',       included: true },
      { label: 'CMS / blog setup',           included: true },
      { label: '3 revision rounds',          included: true },
      { label: 'Analytics dashboard',        included: true },
      { label: 'Landing page CRO audit',     included: true },
    ],
    extraFeatures: [
      { label: 'Custom animations',          included: true },
      { label: 'Lead capture integration',   included: true },
    ],
  },
  {
    id: 'custom-site',
    name: 'Custom',
    tagline: 'When you need a custom-designed, conversion-optimised website',
    price: 'custom',
    currency: 'USD',
    period: 'project',
    delivers: 'Let\'s talk',
    ctaLabel: 'Book a Call',
    features: [
      { label: 'Unlimited pages',            included: true },
      { label: 'Custom UI/UX design',        included: true },
      { label: 'Full SEO strategy',          included: true },
      { label: 'CMS + e-commerce',           included: true },
      { label: 'Unlimited revisions',        included: true },
      { label: 'Performance optimisation',   included: true },
      { label: 'Dedicated project manager',  included: true },
    ],
  },
]

export const APP_PLANS: readonly PricingTier[] = [
  {
    id: 'mvp',
    name: 'MVP',
    tagline: 'Fast, clean, shipped',
    price: 999,
    currency: 'USD',
    period: 'project',
    delivers: '4 weeks',
    ctaLabel: 'Get Started',
    features: [
      { label: 'Product discovery + scoping',   included: true },
      { label: 'UI/UX design in Figma',          included: true },
      { label: 'Full-stack build',               included: true },
      { label: 'API integrations',               included: true },
      { label: '2-week post-launch support',     included: true },
      { label: 'Multi-platform (iOS + Android)', included: false },
    ],
  },
  {
    id: 'fullstack',
    name: 'Full Stack',
    tagline: 'Startups needing a cross-platform mobile app',
    price: 1999,
    currency: 'USD',
    period: 'project',
    delivers: '8 weeks',
    ctaLabel: 'Get Started',
    isRecommended: true,
    badge: 'Popular',
    features: [
      { label: 'Product discovery + scoping',   included: true },
      { label: 'UI/UX design in Figma',          included: true },
      { label: 'React Native / Flutter build',   included: true },
      { label: 'Backend + REST API',             included: true },
      { label: 'Push notifications',             included: true },
      { label: 'App Store + Play Store launch',  included: true },
    ],
    extraFeatures: [
      { label: '4-week post-launch support',     included: true },
      { label: 'Source code handoff',            included: true },
    ],
  },
  {
    id: 'retainer',
    name: 'Retainer',
    tagline: 'Startups that need continuous development without hiring a full-time engineer',
    price: 599,
    currency: 'USD',
    period: 'month',
    ctaLabel: 'Book a Call',
    features: [
      { label: '80–90 hours / month',            included: true },
      { label: 'Dedicated developer',            included: true },
      { label: 'Weekly progress reports',        included: true },
      { label: 'Slack + async updates',          included: true },
      { label: '90-day min. engagement',         included: true },
      { label: 'Cancel anytime after 90 days',   included: true },
    ],
  },
]

// kept for backward compat — Pricing.tsx uses this export name
export const PRICING_TIERS = WEBSITE_PLANS
